version: '3.6'

services:
  nca-control-client:
    image: nca-control-client:latest
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json
